### ISSUE TITLE
npm run dev fails

### ISSUE THREAD

**Issue by Yahav** [CupOfTea696/laravel-mix-imagemin#5]
Using your plugin, this is my setup:
```
mix.imagemin(
    'images/**.*',
    {
        context: 'resources',
    },
    {
        optipng: {
            optimizationLevel: 5
        },
    }
);
```
First run it installed dependencies and asked to run again, when i run it now i get:
```
[yahav@projectName projectName]$ npm run dev

> @ dev /var/www/projectName
> npm run development


> @ development /var/www/projectName
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/var/www/projectName/node_modules/webpack/bin/webpack.js:348
			throw err;
			^

TypeError: Cannot read property 'emit' of undefined
    at CopyPlugin.apply (/var/www/projectName/node_modules/copy-webpack-plugin/dist/index.js:55:20)
    at Compiler.apply (/var/www/projectName/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/var/www/projectName/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/var/www/projectName/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/var/www/projectName/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/var/www/projectName/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/var/www/projectName/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yahav/.npm/_logs/2019-10-21T14_12_19_413Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yahav/.npm/_logs/2019-10-21T14_12_19_429Z-debug.log
```

**Comment by Yahav** [comment]
Had to upgrade to Mix 5 in order to upgrade Webpack
