### ISSUE TITLE
Issue with version()

### ISSUE THREAD

**Issue by michaelaguiar** [CupOfTea696/laravel-mix-imagemin#6]
I am having an issue where imagemin is looking for an image with the versioned query on the name.

Here is my error:
```
Error: ENOENT: no such file or directory, open '/Users/.../public/images/bg-2.jpg?328e6b00961b4ea4ed336e7e8611f033'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at File.read (/Users/.../node_modules/laravel-mix/src/File.js:166:19)
    at File.version (/Users/.../node_modules/laravel-mix/src/File.js:173:25)
    at Manifest.hash (/Users/.../node_modules/laravel-mix/src/Manifest.js:52:65)
    at /Users/.../node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:77:26
    at /Users/.../node_modules/collect.js/dist/methods/each.js:21:22
    at Array.forEach (<anonymous>)
    at Collection.each (/Users/.../node_modules/collect.js/dist/methods/each.js:19:29)
    at CustomTasksPlugin.applyVersioning (/Users/.../node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:76:37)
    at /Users/.../node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:15:22
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/.../node_modules/tapable/lib/Hook.js:154:20)
    at /Users/.../node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/.../node_modules/webpack/lib/Compiler.js:489:39)
    at /Users/.../node_modules/webpack/lib/Compiler.js:298:10
    at /Users/.../node_modules/webpack/lib/Comp    at /Users/.../node_modules/webpack/lib/Comp    at /Users/.../node_modules/webpack/lib/Compiler.js:475:14
    at _next1 (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at onAfterEmit (/Users/.../node_modules/laravel-mix-imagemin/src/ManifestPlugin.js:21:13)
    at _next0 (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at /Users/.../node_modules/copy-webpack-plugin/dist/index.js:116:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/.../node_modules/tapable/lib/Hook.js:154:20)
    at /Users/.../node_modules/webpack/lib/Compiler.js:472:27
    at /Users/.../node_modules/neo-async/async.js:2818:7
    at done (/Users/.../node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/.../node_modules/webpack/lib/Compiler.js:454:33
    at /Users/.../node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:146:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelaguiar/.npm/_logs/2019-10-23T23_05_59_693Z-debug.log
```

And here is my config:
```javascript
let mix = require('laravel-mix');

require('laravel-mix-imagemin');

// All Environments
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .setPublicPath('public');

// Production Only
if (mix.inProduction()) {
    mix.imagemin(
        'images/**.*',
        {
            context: 'resources',
        },
        {
            optipng: {
                optimizationLevel: 7
            },
            pngquant: {
                quality: '65-90',
                speed: 4,
            },
            jpegtran: null,
            plugins: [
                require('imagemin-mozjpeg')({
                    quality: 75,
                    progressive: true,
                }),
            ],
        }
    );

    // Version for cache-busting
    mix.version(['public/images']);
}

```

**Comment by michaelaguiar** [comment]
Seems it grabs the versioned images from the stylesheets, and fails on those because the actual files no longer have the ?XXXX version query on the end.
